import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "@/app/fonts/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${montserrat.className} antialiased`}>
        
        <main>{children}</main>
        
        <footer className="fixed bottom-0 left-0 right-0 bg-white p-4 text-center text-pink-600 border-t border-pink-200">
          <p>&copy; MikaDevSu - Fake Store 2024</p>
        </footer>
        
      </body>
    </html>
  );
}
